[MUTATION RATE]
Names = base_mut_rate
Start = 1e-8
End = 1e-7
Step = 1e-8

[DRUG DOSE]
Names = dose_drug_1_mono
Start = 0.5
End = 0.9
Step = 0.1

[DEFAULT]
Script = ../sims/at50.slim
Directory = /path/to/your/output/dir
SubmissionScript = submission_script.sh
SlimPath = /path/to/slim